apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-service
  namespace: backend 
  labels:
    app: back-end-service
    clusterName: {{ .Values.cluster.name | default "no-cluster-name"}}
    region: {{ .Values.cluster.region | default "US-CENTRAL"}}
spec:
  replicas: {{ .Values.microservices.backEnd.replicas | default "3" }}
  selector:
    matchLabels:
      app: back-end-service
  template:
    metadata:
      labels:
        app: back-end-service
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
