apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-service
  namespace: end-end 
  labels:
    app: testingFramework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80