apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  name: back-end-service
  namespace: backend 
  labels:
    app: back-end-service
    clusterName: {{ .Values.cluster.name | default "no-cluster-name"}}
    region: {{ .Values.cluster.region | default "US-CENTRAL"}}
spec:
  replicas: {{ .Values.backEnd.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        "helm.sh/hook": pre-install,pre-upgrade
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: logLevel
          values: {{ .Values.backEnd.logLevel }}
        - name: storageAddress
          values: {{ .Values.cluster.nfsAddress | default "127.0.0.1" }} 