# import database location
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
 # ref:
 #   semver: "16.3.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      targetNamespace: backend
      chart: postgres
      version: '16.3.1'
      sourceRef:
        kind: OCIRepository
        name: postgres
      interval: 5m
  releaseName: postgres
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
