apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgres
  namespace: backend 
spec:
  type: "oci"
  interval: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts/postgresql