{{- if .Values.microservices.frontEnd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-service 
  namespace: frontend 
  labels:
    app: frontend
    clusterName: {{ .Values.cluster.name | default "no-cluster-name"}}
    region: {{ .Values.cluster.region | default "US-CENTRAL"}}
spec:
  replicas: {{ .Values.microservices.frontEnd.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
          - name: logLevel
            value: {{ .Values.microservices.backEnd.logLevel }}
{{- end }} 