# import database location OCI repo
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    tag: 16.3.1      
---
# use that OCI repo to deploy 
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  targetNamespace: backend
  chartRef:
    kind: OCIRepository
    name: postgres
    namespace: flux-system
  interval: 1m
  values:
    {{- .Values.postgres | toYaml | nindent 6 }}