apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microservices
spec:
  interval: 1m
  chart:
    spec:
      chart: ./services/microservices                        
      sourceRef:
        kind: GitRepository
        namespace: flux-system
        name: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    microservices:
      {{- .Values.microservices| toYaml | nindent 8 }}

    global:
      {{- .Values.global | toYaml | nindent 8 }}

    cluster:
      {{- .Values.cluster | toYaml | nindent 8 }}

