{{- if .Values.microservices.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microservices
spec:
  interval: 10m
  chart:
    spec:
      chart: ./services/microservices
      sourceRef:
        kind: GitRepository
        namespace: flux-system
        name: flux-system
      interval: 10m
  values:
    microservices:
      {{- .Values.microservices| toYaml | nindent 8 }}

    global:
      {{- .Values.global | toYaml | nindent 8 }}

{{- end }}