apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-framework 
spec:
  interval: 10m
  chart:
    spec:
      chart: ./services/integration-testing
      sourceRef:
        kind: GitRepository
        namespace: flux-system
        name: flux-system
      interval: 10m
  values:
    cluster:
      controlNodeIp: 192.10.10.10
      nfsAddress: 192.10.10.11
      region: US-WEST
      {{- .Values.global | toYaml | nindent 6 }}
