# values from main.yaml

# some global values 
global: {}
cluster: {}

# values for individual service that been deployed 
frontEnd:
  enabled: true
  replicas: 3
  logLevel: INFO
  
backEnd:
  enabled: true
  replicas: 3
  logLevel: INFO