# values from main.yaml

# some global values 
global: {}
cluster: {}

# values for individual service that been deployed 
frontEnd:
  enabled: true
  
backEnd:
  enabled: true

postgres:
  nameOverride: "my-postgres"
  global:
    postgresql:
      auth:
        username: admin 
        password: database