apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: common-resources 
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./common
      sourceRef:
        kind: GitRepository
        name: common
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3