apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ./common/
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 10m