apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: common-resources
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./common
      sourceRef:
        kind: GitRepository
        namespace: flux-system
        name: flux-system
      interval: 1m