apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./resources"
  sourceRef:
    kind: GitRepository
    name: cluster