apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-resources
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ./clusters/k3s/resources
      sourceRef:
        kind: GitRepository
        namespace: flux-system
        name: flux-system
      interval: 10m